# =======================================================================
# scMultiPert — Module 5: Multi-modal Fine-tuning via QLoRA (v2.4)
# =======================================================================
# This module executes the dual-stage alignment of BioMistral-7B. It 
# leverages Quantized Low-Rank Adaptation (QLora) to integrate biological 
# soft tokens into the LLM's latent space while maintaining a low memory 
# footprint.
#
# Architectural Features:
#   - Dynamic Latent Injection: The 'SoftTokenCollator' performs on-the-fly 
#     splicing of aligned biological embeddings into the input sequence.
#   - Context Budgeting: Implements strict (2048 - 2) sequence management 
#     to accommodate soft tokens without exceeding the LLM's window.
#   - Information Safeguards: Employs 'Neutral Priors' derived exclusively 
#     from training split keys to ensure zero-leakage evaluation.
#   - Telemetry Sync: Full integration with Weights & Biases (WandB) for 
#     tracking both LoRA and Aligner parameter updates.
#
# Dependencies: transformers, peft, trl, bitsandbytes, torch, datasets, wandb
# =======================================================================

import torch
import wandb
import numpy as np
from pathlib import Path
from typing import Optional, Set, Dict
from datasets import load_dataset
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    BitsAndBytesConfig,
    TrainingArguments,
)
from peft import (
    LoraConfig,
    get_peft_model,
    prepare_model_for_kbit_training,
    PeftModel,
)
from trl import SFTTrainer

# Integration with Module 3 (Alignment) and Module 4 (Corpus)
from module3_alignment import BiomedicalAligner, load_aligner, save_aligner
from module4_corpus import BIO_CONTEXT_TOKEN

# ---------------------------------------------------------------------------
# Global Constants & Environment Configuration
# ---------------------------------------------------------------------------

BIOMISTRAL_MODEL   = "BioMistral/BioMistral-7B"
LLM_HIDDEN_DIM     = 4096
STAGE2_MAX_SEQ_LEN = 2048  # Total context budget including soft tokens.

class Module5Error(Exception): # Base exception for training pipeline failures.
    pass

# ---------------------------------------------------------------------------
# SECTION 1 — SoftTokenCollator: Latent Space Injection Logic
# ---------------------------------------------------------------------------
# A specialized data collator that identifies the BIO_CONTEXT_TOKEN in 
# the tokenized sequence and replaces it with high-dimensional 
# embeddings generated by the BiomedicalAligner.

class SoftTokenCollator:
    def __init__(
        self,
        tokenizer,
        model, # The PeftModel (BioMistral + LoRA)
        aligner: BiomedicalAligner,
        centroid_dict: Dict[str, torch.Tensor],
        var_emb_dict: Dict[str, torch.Tensor],
        train_cell_keys: Set[str],
        train_var_keys: Set[str],
        device: torch.device,
    ):
        self.tokenizer = tokenizer
        self.model = model
        self.aligner = aligner
        self.centroid_dict = centroid_dict
        self.var_emb_dict = var_emb_dict
        self.device = device
        
        self.bio_token_id = tokenizer.convert_tokens_to_ids(BIO_CONTEXT_TOKEN)
        
        # Context Management: Reserving exactly 2 slots for [cell_token, var_token]
        self.max_prompt_len = STAGE2_MAX_SEQ_LEN - 2

        # Leakage-proof Neutral Priors: Derived strictly from training distribution
        self.neutral_cell_prior = self._calculate_train_mean(centroid_dict, train_cell_keys)
        self.neutral_var_prior  = self._calculate_train_mean(var_emb_dict, train_var_keys)

    def _calculate_train_mean(self, emb_dict: dict, train_keys: Set[str]) -> torch.Tensor:
        # Computes the statistical centroid of the training embeddings to serve 
        # as a neutral context for cross-modal attention.
        valid_embs = [emb_dict[k] for k in train_keys if k in emb_dict]
        if not valid_embs:
            print("[Warning] No training keys found for prior calculation. Falling back to global mean.")
            return torch.stack(list(emb_dict.values())).mean(dim=0).to(self.device)
        return torch.stack(valid_embs).mean(dim=0).to(self.device)

    def __call__(self, features: list) -> dict:
        # 1. Tokenization & Truncation (Safe-buffer aware)
        texts = [f["messages"][-1]["content"] if isinstance(f["messages"], list) else f["text"] for f in features]
        batch = self.tokenizer(
            texts, 
            return_tensors="pt", 
            padding=True, 
            truncation=True, 
            max_length=self.max_prompt_len
        )
        input_ids = batch["input_ids"].to(self.device)
        attn_mask = batch["attention_mask"].to(self.device)

        # 2. Latent Projection: Mapping discrete tokens to LLM embeddings
        inputs_embeds = self.model.get_input_embeddings()(input_ids)
        
        # 3. Aligner Input Orchestration
        cell_batch, var_batch, bio_indices = [], [], []
        
        for i, f in enumerate(features):
            if not f.get("has_bio_context"): continue
            
            key, modality = f.get("embedding_key"), f.get("modality")
            bio_indices.append(i)
            
            # Modal-specific context filling
            if modality == "scrna":
                cell_batch.append(self.centroid_dict.get(key, self.neutral_cell_prior))
                var_batch.append(self.neutral_var_prior)
            else: # modality == "mave"
                cell_batch.append(self.neutral_cell_prior)
                var_batch.append(self.var_emb_dict.get(key, self.neutral_var_prior))

        # 4. Bio-Token Synthesis via BiomedicalAligner
        if bio_indices:
            c_tensor = torch.stack(cell_batch).to(self.device)
            v_tensor = torch.stack(var_batch).to(self.device)
            
            with torch.no_grad():
                # Cross-attention fusion: Aligned representation [B_bio, 2, 4096]
                soft_tokens, _ = self.aligner(c_tensor, v_tensor)

            # 5. Latent Splicing: Injecting soft tokens into the hidden state
            for local_idx, batch_idx in enumerate(bio_indices):
                # Locate the injection point (BIO_CONTEXT_TOKEN)
                pos = (input_ids[batch_idx] == self.bio_token_id).nonzero(as_tuple=True)[0]
                if len(pos) > 0:
                    p = pos[0].item()
                    # Replace 1 discrete token with 2 continuous soft tokens
                    # Sequence length increases by 1 (buffer managed in Step 1)
                    prefix = inputs_embeds[batch_idx, :p]
                    suffix = inputs_embeds[batch_idx, p+1:]
                    inputs_embeds[batch_idx] = torch.cat([prefix, soft_tokens[local_idx], suffix[:-1]], dim=0)

        # Labels for Causal LM training (ignoring pad tokens)
        labels = input_ids.clone()
        labels[labels == self.tokenizer.pad_token_id] = -100

        return {
            "inputs_embeds": inputs_embeds,
            "attention_mask": attn_mask,
            "labels": labels
        }

# ---------------------------------------------------------------------------
# SECTION 2 — QLoRA Configuration & Resource Management
# ---------------------------------------------------------------------------
# Optimizes the training process for 4-bit quantization, allowing the 
# 7B parameter model to be fine-tuned on consumer-grade or mid-range hardware.

def get_qlora_config():
    return LoraConfig(
        r=16, lora_alpha=32,
        target_modules=["q_proj", "v_proj", "k_proj", "o_proj"],
        lora_dropout=0.05, bias="none",
        task_type="CAUSAL_LM"
    )

def load_biomistral_4bit():
    # Configure 4-bit Quantization (NF4) with double quantization for stability
    bnb_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_compute_dtype=torch.float16,
        bnb_4bit_use_double_quant=True,
    )
    model = AutoModelForCausalLM.from_pretrained(
        BIOMISTRAL_MODEL,
        quantization_config=bnb_config,
        device_map="auto",
        trust_remote_code=True
    )
    # Prepare model for gradient checkpointing and k-bit efficiency
    model = prepare_model_for_kbit_training(model)
    return model

# ---------------------------------------------------------------------------
# SECTION 3 — Stage 2 Execution Pipeline
# ---------------------------------------------------------------------------
# Orchestrates the simultaneous fine-tuning of the LoRA adapters and the 
# BiomedicalAligner, establishing the multi-modal reasoning capability.

def run_stage2(
    aligner_path: str,
    centroid_dict: dict,
    var_emb_dict: dict,
    corpus_paths: dict,
    output_dir: str = "finetuned_stage2/"
):
    print("=" * 55)
    print("scMultiPert | Module 5: Stage 2 Fine-tuning (v2.4)")
    print("=" * 55)

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    tokenizer = AutoTokenizer.from_pretrained(BIOMISTRAL_MODEL)
    tokenizer.pad_token = tokenizer.eos_token

    # 1. Dataset Initialization & Leakage Control
    dataset = load_dataset("json", data_files=corpus_paths["train_path"], split="train")
    train_ds = dataset.filter(lambda x: x["split"] == "train")
    
    # Identify training-specific keys for neutral prior calculation
    train_cell_keys = set(train_ds.filter(lambda x: x["modality"] == "scrna")["embedding_key"])
    train_var_keys  = set(train_ds.filter(lambda x: x["modality"] == "mave")["embedding_key"])

    # 2. Model Architecture Loading
    model = load_biomistral_4bit()
    model = get_peft_model(model, get_qlora_config())
    
    # Initialize and Unfreeze Aligner for joint optimization
    aligner = load_aligner(aligner_path)
    aligner.to(device)
    aligner.unfreeze() 

    # 3. Experiment Tracking: Telemetry Setup
    wandb.init(
        project="scMultiPert",
        name="stage2-soft-tokens",
        config={
            "aligner_params": aligner.count_parameters(),
            "max_seq_len": STAGE2_MAX_SEQ_LEN
        }
    )

    # 4. Collator Initialization with Architectural Sync
    collator = SoftTokenCollator(
        tokenizer=tokenizer,
        model=model,
        aligner=aligner,
        centroid_dict=centroid_dict,
        var_emb_dict=var_emb_dict,
        train_cell_keys=train_cell_keys,
        train_var_keys=train_var_keys,
        device=device
    )

    # 5. Hyperparameter Configuration
    training_args = TrainingArguments(
        output_dir=output_dir,
        per_device_train_batch_size=4,
        gradient_accumulation_steps=4,
        learning_rate=2e-4,
        num_train_epochs=3,
        logging_steps=10,
        save_strategy="epoch",
        bf16=torch.cuda.is_bf16_supported(),
        remove_unused_columns=False # Required to pass custom dictionary keys
    )

    # 6. Trainer Instantiation & Multi-modal Optimization
    trainer = SFTTrainer(
        model=model,
        args=training_args,
        train_dataset=train_ds,
        data_collator=collator,
        max_seq_length=STAGE2_MAX_SEQ_LEN,
    )

    print("[Module 5] Starting Stage 2 Training Phase...")
    trainer.train()

    # 7. Persistence: Artifact Serialization
    model.save_pretrained(f"{output_dir}/llm_adapter")
    save_aligner(aligner, output_dir, tag="stage2_final")
    
    print(f"[Module 5] Training Complete. Artifacts saved to: {output_dir}")