"""
scMultiPert — Module 4: Corpus Builder
============================================
Builds the instruction-tuning dataset for Stage 1 (text-only) and Stage 2 
(multi-modal soft token) training of the scMultiPert biomedical assistant.

This module consumes embeddings and metadata from Module 2 (Encoders) and 
structures them into ChatML-formatted training examples. It implements 
gene-based data splitting to prevent information leakage between training 
and test sets, critical for evaluating model generalization to unseen genes.

Architecture Integration:
  - Module 1 (Preprocessing): Provides standardized AnnData and DataFrames.
  - Module 2 (Encoders): Provides cell_embeddings [N, 256], var_embeddings [M, 320],
    var_texts, var_ids, and crispr_texts.
  - Module 3 (Alignment): Consumes centroids computed here for Stage 2 training.
  - Module 5 (Training): Consumes the train_corpus.jsonl and test_corpus.jsonl 
    generated by this module.
  - Validation: Compatible with validate_pipeline.py checks for gene leakage,
    template diversity, and bio-context token presence.

Data Flow:
  1. Compute perturbation centroids from cell embeddings (mean pooling per perturbation).
  2. Build modality-specific ChatML examples (MAVE, scRNA, CRISPR).
  3. Extract dynamic gene vocabulary from all modalities.
  4. Apply gene-based split (no gene overlap between train/test).
  5. Serialize to JSONL with metadata for downstream consumption.

Dependencies: torch, pandas, anndata, numpy, json, random, pathlib
"""

import json
import random
import torch
import numpy as np
import pandas as pd
import anndata as ad
from pathlib import Path
from dataclasses import dataclass, asdict
from typing import Optional, List, Dict, Set, Tuple, Any

# ---------------------------------------------------------------------------
# SECTION 0 — Custom Exceptions
# ---------------------------------------------------------------------------

class Module4Error(Exception):
    """Base class for Module 4 domain-specific errors."""
    pass


class SplitError(Module4Error):
    """Raised when gene-based data splitting encounters invalid configuration."""
    pass


class AlignmentError(Module4Error):
    """Raised when data misalignment detected between M1/M2/M3 outputs."""
    pass


class CorpusBuilderError(Module4Error):
    """Raised when corpus construction fails due to data quality issues."""
    pass


# ---------------------------------------------------------------------------
# SECTION 1 — Constants & Templates
# ---------------------------------------------------------------------------

SYSTEM_PROMPT = (
    "You are scMultiPert, a perturbation-aware biomedical assistant "
    "specialized in predicting and explaining the effects of genetic "
    "perturbations on cellular state and protein function."
)

# Token marking injection point for soft embeddings in Stage 2
BIO_CONTEXT_TOKEN = "<|BIO_CONTEXT|>"

# Expected embedding dimensions (from Module 2 encoders)
GENEFORMER_DIM = 256
ESM2_8M_DIM = 320

# Question templates for MAVE (variant effect) modality
MAVE_QUESTION_TEMPLATES = [
    "What is the functional effect of {gene_symbol} variant {variant_id}?",
    "How does the {aa_ref}{position}{aa_alt} substitution in {gene_symbol} affect function?",
    "What does the SGE score {score} tell us about {variant_id}?",
    "Predict the functional impact of {gene_symbol} variant {variant_id} based on its SGE score of {score}.",
    "Is {gene_symbol} variant {variant_id} likely to be pathogenic?",
]

# Question templates for scRNA-seq (transcriptional response) modality
SCRNA_QUESTION_TEMPLATES = [
    "What is the transcriptional response to {perturbation} in K562 cells?",
    "Describe the gene expression changes following {perturbation} perturbation.",
    "Predict the molecular phenotype of cells with {perturbation} activation.",
    "How does {perturbation} perturbation alter the transcriptome of K562 cells?",
    "Identify the marker genes characterizing the {perturbation} perturbation state.",
]

# Question templates for CRISPR (gene essentiality) modality
CRISPR_QUESTION_TEMPLATES = [
    "Is {gene} essential in {lineage} cell lines?",
    "What is the fitness effect of knocking out {gene} in {lineage} tissue?",
    "Does loss of {gene} function impair viability in {lineage} cancer models?",
    "Predict the essentiality of {gene} based on CRISPR screening data in {lineage}.",
    "What percentage of {lineage} cell lines show dependency on {gene}?",
]


# ---------------------------------------------------------------------------
# SECTION 2 — Data Structures
# ---------------------------------------------------------------------------

@dataclass
class ChatMLExample:
    """
    Structured container for instruction-tuning examples in ChatML format.
    
    Attributes:
        messages: List of dicts with 'role' and 'content' keys following ChatML spec.
        modality: Source modality identifier ('mave', 'scrna', or 'crispr').
        has_bio_context: Whether this example requires soft token injection.
        gene_id: Primary gene identifier (supports combinatorial "A+B" format).
        embedding_key: Key for retrieving pre-computed embeddings (variant_id or pert_label).
        bio_context_meta: Metadata dict with expected dimensions for validation.
        split: Data split assignment ('train' or 'test').
    """
    messages: List[Dict[str, str]]
    modality: str
    has_bio_context: bool = False
    gene_id: Optional[str] = None
    embedding_key: Optional[str] = None
    bio_context_meta: Optional[Dict[str, Any]] = None
    split: str = "train"

    def to_dict(self) -> Dict[str, Any]:
        """Serialize to dictionary for JSONL serialization."""
        return asdict(self)


# ---------------------------------------------------------------------------
# SECTION 3 — Centroid Computation
# ---------------------------------------------------------------------------

def compute_perturbation_centroids(
    cell_embeddings: torch.Tensor, 
    cell_metadata: pd.DataFrame
) -> Dict[str, torch.Tensor]:
    """
    Compute mean embedding vectors for each unique perturbation condition.
    
    Aggregates single-cell embeddings by perturbation label to create 
    representative vectors for each experimental condition. Control cells
    are excluded from centroid computation as they represent baseline states
    rather than perturbation responses.
    
    Args:
        cell_embeddings: Tensor of shape [N_cells, 256] from GeneformerEncoder.
        cell_metadata: DataFrame with columns 'is_control', 'embedding_label', 
                      and 'embedding_idx' synchronized with cell_embeddings.
    
    Returns:
        Dictionary mapping perturbation labels (e.g., "CDKN1A", "FOXA1+TBX2") 
        to their mean embedding tensors [256].
    
    Raises:
        AlignmentError: If cell_embeddings and cell_metadata have mismatched lengths.
        CorpusBuilderError: If no valid perturbation cells found after filtering controls.
    """
    if len(cell_embeddings) != len(cell_metadata):
        raise AlignmentError(
            f"Cell embeddings ({len(cell_embeddings)}) and metadata ({len(cell_metadata)}) "
            f"have mismatched lengths. Ensure Module 2 outputs are synchronized."
        )
    
    # Filter to perturbation cells only (exclude controls)
    pert_mask = ~cell_metadata["is_control"]
    pert_metadata = cell_metadata[pert_mask].copy()
    
    if len(pert_metadata) == 0:
        raise CorpusBuilderError(
            "No perturbation cells found after filtering controls. "
            "Check 'is_control' labels in Module 1 output."
        )
    
    centroids = {}
    
    # Group by embedding_label (handles both single and combinatorial perturbations)
    for label, group in pert_metadata.groupby("embedding_label"):
        indices = group["embedding_idx"].tolist()
        # Mean pooling across cells for this perturbation
        centroid = cell_embeddings[indices].mean(dim=0).cpu()
        centroids[label] = centroid
    
    return centroids


# ---------------------------------------------------------------------------
# SECTION 4 — Example Builders
# ---------------------------------------------------------------------------

def build_mave_examples(
    mave_df: pd.DataFrame, 
    var_texts: List[str], 
    var_ids: List[str], 
    seed: int = 42
) -> List[ChatMLExample]:
    """
    Construct ChatML examples from MAVE variant functional data.
    
    Creates instruction-following examples for protein variant effect prediction.
    Each example pairs a randomly selected question template with structured
    variant metadata and the pre-generated text description from Module 2.
    
    Args:
        mave_df: DataFrame from Module 1 with variant annotations including
                'variant_id', 'gene_symbol', 'aa_ref', 'aa_alt', 'position', 
                'sge_score', 'function_class'.
        var_texts: List of structured text descriptions from ESMVariantEncoder.
        var_ids: List of variant identifiers corresponding to var_texts.
        seed: Random seed for reproducible template selection.
    
    Returns:
        List of ChatMLExample objects for MAVE modality.
    
    Raises:
        AlignmentError: If var_texts and var_ids have mismatched lengths.
        CorpusBuilderError: If no valid variants found in lookup mapping.
    """
    if len(var_texts) != len(var_ids):
        raise AlignmentError(
            f"MAVE text/ID misalignment: {len(var_texts)} texts vs {len(var_ids)} IDs. "
            f"Re-run Module 2 ESMVariantEncoder to regenerate synchronized outputs."
        )
    
    # Build lookup for efficient variant retrieval
    mave_lookup = {row["variant_id"]: row for _, row in mave_df.iterrows()}
    examples = []
    rng = random.Random(seed)
    
    for vid, text in zip(var_ids, var_texts):
        if vid not in mave_lookup:
            continue  # Skip variants not in current gene set
        
        row = mave_lookup[vid]
        
        # Format question with random template
        question = rng.choice(MAVE_QUESTION_TEMPLATES).format(
            gene_symbol=row["gene_symbol"],
            variant_id=vid,
            aa_ref=row["aa_ref"],
            aa_alt=row["aa_alt"],
            position=int(row["position"]),
            score=f"{row['sge_score']:.2f}"
        )
        
        # Construct ChatML message sequence with bio-context token for Stage 2
        example = ChatMLExample(
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": f"{BIO_CONTEXT_TOKEN} {question}"},
                {"role": "assistant", "content": text}
            ],
            modality="mave",
            has_bio_context=True,
            gene_id=row["gene_symbol"],
            embedding_key=vid,
            bio_context_meta={
                "expected_cell_dim": GENEFORMER_DIM,
                "expected_var_dim": ESM2_8M_DIM,
                "sge_score": float(row["sge_score"]),
                "function_class": row["function_class"]
            }
        )
        examples.append(example)
    
    if not examples:
        raise CorpusBuilderError(
            "No MAVE examples generated. Check variant_id alignment between "
            "mave_df and var_ids from Module 2."
        )
    
    return examples


def build_scrna_examples(
    adata: ad.AnnData, 
    centroids: Dict[str, torch.Tensor], 
    seed: int = 42
) -> List[ChatMLExample]:
    """
    Construct ChatML examples from scRNA-seq perturbation centroids.
    
    Generates instruction-tuning examples for transcriptional response prediction.
    Each perturbation centroid is described using the top differentially 
    expressed genes as a biological signature.
    
    Args:
        adata: AnnData object from Module 1 with raw counts and perturbation 
               metadata in obs.
        centroids: Dictionary mapping perturbation labels to mean embedding 
                  vectors from compute_perturbation_centroids().
        seed: Random seed for reproducible question generation.
    
    Returns:
        List of ChatMLExample objects for scRNA modality.
    
    Raises:
        CorpusBuilderError: If centroids dictionary is empty.
        AlignmentError: If perturbation labels in centroids not found in adata.
    """
    if not centroids:
        raise CorpusBuilderError(
            "Empty centroids dictionary provided. Run compute_perturbation_centroids() "
            "on valid cell embeddings first."
        )
    
    examples = []
    rng = random.Random(seed)
    
    for pert_label, centroid_emb in centroids.items():
        # Validate perturbation exists in AnnData
        if pert_label not in adata.obs["perturbation"].values:
            raise AlignmentError(
                f"Perturbation label '{pert_label}' in centroids not found in "
                f"AnnData obs. Check Module 1 preprocessing consistency."
            )
        
        # Extract mean expression for this perturbation to generate biological description
        pert_mask = adata.obs["perturbation"] == pert_label
        mean_expr = adata[pert_mask].X.mean(axis=0)
        
        # Handle sparse matrix conversion
        if hasattr(mean_expr, "A1"):
            mean_expr = mean_expr.A1
        
        # Get top 5 marker genes as transcriptional signature
        top_idx = np.argsort(mean_expr)[-5:]
        top_genes = adata.var_names[top_idx].tolist()
        
        # Construct biologically grounded response
        response = (
            f"The perturbation of {pert_label} leads to a distinct transcriptional state "
            f"characterized by high expression of {', '.join(top_genes)}. "
            f"This suggests a significant shift in cellular homeostasis and regulatory "
            f"networks associated with {pert_label} function."
        )
        
        question = rng.choice(SCRNA_QUESTION_TEMPLATES).format(perturbation=pert_label)
        
        example = ChatMLExample(
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": f"{BIO_CONTEXT_TOKEN} {question}"},
                {"role": "assistant", "content": response}
            ],
            modality="scrna",
            has_bio_context=True,
            gene_id=pert_label,  # Supports "GeneA+GeneB" format
            embedding_key=pert_label,
            bio_context_meta={
                "expected_cell_dim": GENEFORMER_DIM,
                "expected_var_dim": ESM2_8M_DIM,
                "n_cells": int(pert_mask.sum()),
                "top_markers": top_genes
            }
        )
        examples.append(example)
    
    return examples


def build_crispr_examples(
    crispr_texts: List[str], 
    crispr_agg: pd.DataFrame, 
    seed: int = 42
) -> List[ChatMLExample]:
    """
    Construct ChatML examples from CRISPR screening data.
    
    Creates text-only instruction examples for gene essentiality prediction.
    Unlike MAVE and scRNA modalities, CRISPR examples do not use soft token
    injection (has_bio_context=False) as they rely purely on textual descriptions
    of fitness scores and essentiality rates.
    
    Args:
        crispr_texts: List of structured text descriptions from Module 2 
                     encode_crispr_as_text().
        crispr_agg: DataFrame with aggregated CRISPR statistics including 
                   'gene', 'lineage', 'mean_fitness', 'essential_rate'.
        seed: Random seed for reproducible question generation.
    
    Returns:
        List of ChatMLExample objects for CRISPR modality.
    
    Raises:
        AlignmentError: If crispr_texts and crispr_agg have mismatched lengths.
    """
    if len(crispr_texts) != len(crispr_agg):
        raise AlignmentError(
            f"CRISPR text/data misalignment: {len(crispr_texts)} texts vs "
            f"{len(crispr_agg)} aggregated rows. Re-run Module 2 CRISPR encoding."
        )
    
    examples = []
    rng = random.Random(seed)
    
    for i, (_, row) in enumerate(crispr_agg.iterrows()):
        question = rng.choice(CRISPR_QUESTION_TEMPLATES).format(
            gene=row["gene"],
            lineage=row["lineage"]
        )
        
        example = ChatMLExample(
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": question},  # No bio-context token for text-only
                {"role": "assistant", "content": crispr_texts[i]}
            ],
            modality="crispr",
            has_bio_context=False,  # Pure text modality
            gene_id=row["gene"],
            embedding_key=None,
            bio_context_meta={
                "mean_fitness": float(row["mean_fitness"]),
                "essential_rate": float(row["essential_rate"]),
                "n_cell_lines": int(row["n_cell_lines"])
            }
        )
        examples.append(example)
    
    return examples


# ---------------------------------------------------------------------------
# SECTION 5 — Gene-Based Data Splitting
# ---------------------------------------------------------------------------

def _extract_gene_components(gene_id: Optional[str]) -> Set[str]:
    """
    Parse gene identifier into constituent gene symbols.
    
    Handles both single genes ("BRCA1") and combinatorial perturbations 
    ("CDKN1A+FOXA1") by splitting on '+' delimiter and stripping whitespace.
    
    Args:
        gene_id: Gene identifier string or None.
    
    Returns:
        Set of individual gene symbols. Empty set if gene_id is None.
    """
    if gene_id is None:
        return set()
    
    # Handle combinatorial format: "GeneA+GeneB" -> {"GeneA", "GeneB"}
    components = {g.strip() for g in gene_id.split("+")}
    return components


def split_by_gene(
    examples: List[ChatMLExample],
    all_gene_symbols: Set[str],
    test_fraction: float = 0.15,
    seed: int = 42
) -> List[ChatMLExample]:
    """
    Assign examples to train/test splits ensuring no gene overlap.
    
    Implements strict gene-level holdout to prevent data leakage. For 
    combinatorial perturbations (e.g., "A+B"), the example is assigned to 
    test if ANY component gene is in the test set. This ensures the model
    is evaluated on true zero-shot gene prediction.
    
    Validation compatibility:
      - Checked by validate_pipeline.py check_gene_leakage (CriticalLeakageError 
        if intersection non-empty).
      - Required for M4.leakage_pass validation metric.
    
    Args:
        examples: List of ChatMLExample objects to split.
        all_gene_symbols: Set of all unique genes across all modalities.
        test_fraction: Proportion of genes to hold out for testing (0.0-1.0).
        seed: Random seed for reproducible gene selection.
    
    Returns:
        List of ChatMLExample objects with 'split' attribute assigned.
    
    Raises:
        SplitError: If gene vocabulary is empty or test_fraction invalid.
    """
    if not all_gene_symbols:
        raise SplitError(
            "Gene vocabulary is empty. Ensure Module 1 outputs contain valid "
            "gene symbols in 'gene_symbol' and 'perturbed_genes' columns."
        )
    
    if not (0.0 < test_fraction < 1.0):
        raise SplitError(
            f"Invalid test_fraction: {test_fraction}. Must be between 0.0 and 1.0."
        )
    
    rng = random.Random(seed)
    n_test = max(1, int(len(all_gene_symbols) * test_fraction))
    test_genes = set(rng.sample(sorted(all_gene_symbols), k=n_test))
    
    print(f"[Module 4] Gene-based split: {len(test_genes)} test genes "
          f"({len(all_gene_symbols) - len(test_genes)} train genes)")
    print(f"[Module 4] Test gene sample: {list(test_genes)[:5]}...")
    
    for example in examples:
        if example.gene_id is None:
            # Default to train for examples without gene association
            example.split = "train"
            continue
        
        # Extract component genes (handles combinatorial)
        components = _extract_gene_components(example.gene_id)
        
        # Assign to test if ANY component is in test set (conservative)
        if components.intersection(test_genes):
            example.split = "test"
        else:
            example.split = "train"
    
    # Validation: Report split distribution
    n_train = sum(1 for ex in examples if ex.split == "train")
    n_test = sum(1 for ex in examples if ex.split == "test")
    print(f"[Module 4] Example distribution: {n_train} train, {n_test} test")
    
    return examples


# ---------------------------------------------------------------------------
# SECTION 6 — Gene Vocabulary Extraction
# ---------------------------------------------------------------------------

def extract_gene_vocabulary(modalities: Dict[str, Any]) -> Set[str]:
    """
    Compile comprehensive gene vocabulary from all data modalities.
    
    Aggregates gene symbols from:
      - MAVE: 'gene_symbol' column
      - CRISPR: 'gene' column  
      - scRNA: 'perturbed_genes' column (handles list format and combinatorial)
    
    This vocabulary drives the gene-based splitting strategy to prevent leakage.
    
    Args:
        modalities: Dictionary from Module 1 with 'scrna', 'crispr', 'mave' keys.
    
    Returns:
        Set of all unique gene symbols across modalities.
    
    Raises:
        CorpusBuilderError: If any modality is missing required gene columns.
    """
    all_genes = set()
    
    # MAVE genes
    if "gene_symbol" in modalities["mave"].columns:
        all_genes.update(modalities["mave"]["gene_symbol"].unique())
    else:
        raise CorpusBuilderError(
            "MAVE DataFrame missing 'gene_symbol' column. "
            "Check Module 1 load_multi_mave() output."
        )
    
    # CRISPR genes
    if "gene" in modalities["crispr"].columns:
        all_genes.update(modalities["crispr"]["gene"].unique())
    else:
        raise CorpusBuilderError(
            "CRISPR DataFrame missing 'gene' column. "
            "Check Module 1 load_depmap_crispr() output."
        )
    
    # scRNA genes (handles list format in perturbed_genes)
    if "perturbed_genes" in modalities["scrna"].obs.columns:
        for pert_genes in modalities["scrna"].obs["perturbed_genes"]:
            if isinstance(pert_genes, list):
                all_genes.update(pert_genes)
            elif isinstance(pert_genes, str):
                # Handle string representation if needed
                all_genes.update(_extract_gene_components(pert_genes))
    else:
        raise CorpusBuilderError(
            "scRNA AnnData missing 'perturbed_genes' column. "
            "Check Module 1 load_norman2019() output."
        )
    
    # Remove None/empty entries
    all_genes = {g for g in all_genes if g and isinstance(g, str)}
    
    print(f"[Module 4] Extracted gene vocabulary: {len(all_genes)} unique genes")
    
    return all_genes


# ---------------------------------------------------------------------------
# SECTION 7 — Serialization
# ---------------------------------------------------------------------------

def serialize_corpus(
    examples: List[ChatMLExample],
    output_dir: Path,
    centroids: Dict[str, torch.Tensor]
) -> Tuple[str, str]:
    """
    Write training corpus to JSONL and centroids to PyTorch format.
    
    Outputs:
      - train_corpus.jsonl: Training examples with split='train'
      - test_corpus.jsonl: Test examples with split='test'
      - scrna_centroids.pt: Tensor dictionary for Module 5/6 retrieval
    
    Args:
        examples: List of ChatMLExample objects with assigned splits.
        output_dir: Path object for output directory.
        centroids: Dictionary of perturbation centroids for Stage 2 training.
    
    Returns:
        Tuple of (train_path, test_path) as strings.
    
    Raises:
        CorpusBuilderError: If output directory cannot be created or is not writable.
    """
    try:
        output_dir.mkdir(parents=True, exist_ok=True)
    except OSError as e:
        raise CorpusBuilderError(
            f"Cannot create output directory {output_dir}: {e}"
        )
    
    # Split examples
    train_examples = [ex for ex in examples if ex.split == "train"]
    test_examples = [ex for ex in examples if ex.split == "test"]
    
    # Serialize to JSONL
    train_path = output_dir / "train_corpus.jsonl"
    test_path = output_dir / "test_corpus.jsonl"
    
    with open(train_path, "w", encoding="utf-8") as f:
        for ex in train_examples:
            f.write(json.dumps(ex.to_dict(), ensure_ascii=False) + "\n")
    
    with open(test_path, "w", encoding="utf-8") as f:
        for ex in test_examples:
            f.write(json.dumps(ex.to_dict(), ensure_ascii=False) + "\n")
    
    # Save centroids for Module 5 soft token retrieval
    centroids_path = output_dir / "scrna_centroids.pt"
    torch.save(centroids, centroids_path)
    
    print(f"[Module 4] Serialized corpus:")
    print(f"  Train: {train_path} ({len(train_examples)} examples)")
    print(f"  Test:  {test_path} ({len(test_examples)} examples)")
    print(f"  Centroids: {centroids_path} ({len(centroids)} perturbations)")
    
    return str(train_path), str(test_path)


# ---------------------------------------------------------------------------
# SECTION 8 — Main Entry Point
# ---------------------------------------------------------------------------

def build_corpus(
    modalities: Dict[str, Any],
    m2_outputs: Dict[str, Any],
    output_dir: str = "corpus/",
    test_fraction: float = 0.15,
    seed: int = 42
) -> Dict[str, Any]:
    """
    Main execution flow for corpus construction.
    
    Orchestrates the complete pipeline from embeddings to serialized training
    data, ensuring compatibility with all upstream modules and validation
    requirements.
    
    Integration Points:
      - Module 1: Consumes 'scrna' (AnnData), 'crispr' (DataFrame), 'mave' (DataFrame).
      - Module 2: Consumes cell_embeddings, cell_metadata, var_embeddings, 
                 var_texts, var_ids, crispr_texts, crispr_agg.
      - Module 3: Provides centroids for potential cross-modal validation.
      - Validation: Outputs compatible with validate_pipeline.py checks.
    
    Args:
        modalities: Dictionary from Module 1 load_all_modalities().
        m2_outputs: Dictionary from Module 2 encode_all_modalities().
        output_dir: Directory path for output files.
        test_fraction: Fraction of genes to hold out for testing.
        seed: Random seed for reproducibility.
    
    Returns:
        Dictionary containing:
          - train_path: Path to train_corpus.jsonl
          - test_path: Path to test_corpus.jsonl
          - centroids: Dictionary of perturbation centroids
          - gene_vocabulary: Set of all genes used for splitting
          - n_examples: Total number of examples generated
          - modality_counts: Dict with counts per modality
    
    Raises:
        Module4Error: If any stage of corpus construction fails.
    """
    print("=" * 60)
    print("scMultiPert | Module 4: Corpus Builder")
    print("=" * 60)
    
    # Stage 1: Compute perturbation centroids for Stage 2 training
    print("\n[Stage 1/5] Computing perturbation centroids...")
    try:
        centroids = compute_perturbation_centroids(
            m2_outputs["cell_embeddings"],
            m2_outputs["cell_metadata"]
        )
        print(f"  Computed {len(centroids)} perturbation centroids")
    except Exception as e:
        raise CorpusBuilderError(f"Centroid computation failed: {e}") from e
    
    # Stage 2: Build modality-specific examples
    print("\n[Stage 2/5] Building MAVE examples...")
    try:
        mave_examples = build_mave_examples(
            modalities["mave"],
            m2_outputs["var_texts"],
            m2_outputs["var_ids"],
            seed=seed
        )
        print(f"  Generated {len(mave_examples)} MAVE examples")
    except Exception as e:
        raise CorpusBuilderError(f"MAVE example building failed: {e}") from e
    
    print("\n[Stage 3/5] Building scRNA-seq examples...")
    try:
        scrna_examples = build_scrna_examples(
            modalities["scrna"],
            centroids,
            seed=seed
        )
        print(f"  Generated {len(scrna_examples)} scRNA examples")
    except Exception as e:
        raise CorpusBuilderError(f"scRNA example building failed: {e}") from e
    
    print("\n[Stage 4/5] Building CRISPR examples...")
    try:
        crispr_examples = build_crispr_examples(
            m2_outputs["crispr_texts"],
            m2_outputs["crispr_agg"],
            seed=seed
        )
        print(f"  Generated {len(crispr_examples)} CRISPR examples")
    except Exception as e:
        raise CorpusBuilderError(f"CRISPR example building failed: {e}") from e
    
    # Combine all examples
    all_examples = mave_examples + scrna_examples + crispr_examples
    
    modality_counts = {
        "mave": len(mave_examples),
        "scrna": len(scrna_examples),
        "crispr": len(crispr_examples),
        "total": len(all_examples)
    }
    print(f"\n[Summary] Total examples: {len(all_examples)}")
    print(f"  MAVE:   {len(mave_examples)}")
    print(f"  scRNA:  {len(scrna_examples)}")
    print(f"  CRISPR: {len(crispr_examples)}")
    
    # Stage 3: Extract gene vocabulary for splitting
    print("\n[Stage 5/5] Extracting gene vocabulary and applying split...")
    try:
        gene_vocab = extract_gene_vocabulary(modalities)
    except Exception as e:
        raise CorpusBuilderError(f"Gene vocabulary extraction failed: {e}") from e
    
    # Stage 4: Apply gene-based split
    try:
        all_examples = split_by_gene(
            all_examples,
            gene_vocab,
            test_fraction=test_fraction,
            seed=seed
        )
    except Exception as e:
        raise SplitError(f"Gene-based splitting failed: {e}") from e
    
    # Stage 5: Serialize outputs
    print("\n[Serialization] Writing corpus files...")
    out_path = Path(output_dir)
    try:
        train_path, test_path = serialize_corpus(all_examples, out_path, centroids)
    except Exception as e:
        raise CorpusBuilderError(f"Serialization failed: {e}") from e
    
    print("\n" + "=" * 60)
    print("Module 4 Complete")
    print("=" * 60)
    
    return {
        "train_path": train_path,
        "test_path": test_path,
        "centroids": centroids,
        "gene_vocabulary": gene_vocab,
        "n_examples": len(all_examples),
        "modality_counts": modality_counts
    }


# ---------------------------------------------------------------------------
# SECTION 9 — Validation Helpers (for validate_pipeline.py)
# ---------------------------------------------------------------------------

def validate_corpus_integrity(corpus_paths: Dict[str, str]) -> Dict[str, Any]:
    """
    Validate corpus files for pipeline integrity checks.
    
    Helper function for validate_pipeline.py to perform M4 checks without
    reloading the full build_corpus logic. Validates:
      - Gene leakage between splits (CriticalLeakageError if detected)
      - Template diversity per modality
      - BIO_CONTEXT_TOKEN presence in bio-context examples
    
    Args:
        corpus_paths: Dictionary with 'train_path' and 'test_path' keys.
    
    Returns:
        Validation report dictionary with check results.
    
    Raises:
        CriticalLeakageError: If gene overlap detected between train/test.
        CorpusBuilderError: If files cannot be read.
    """
    from collections import Counter
    
    def load_jsonl(path: str) -> List[Dict]:
        examples = []
        try:
            with open(path, 'r', encoding='utf-8') as f:
                for line in f:
                    examples.append(json.loads(line.strip()))
        except Exception as e:
            raise CorpusBuilderError(f"Cannot read {path}: {e}") from e
        return examples
    
    def extract_template(question: str) -> str:
        """Extract template signature from question text."""
        # Simple heuristic: first 20 chars + last 20 chars
        question = question.replace(BIO_CONTEXT_TOKEN, "").strip()
        if len(question) <= 40:
            return question
        return question[:20] + "..." + question[-20:]
    
    train_ex = load_jsonl(corpus_paths["train_path"])
    test_ex = load_jsonl(corpus_paths["test_path"])
    
    results = {}
    
    # Check 1: Gene leakage (CRITICAL)
    train_genes = set()
    test_genes = set()
    
    for ex in train_ex:
        if ex.get("gene_id"):
            train_genes.update(_extract_gene_components(ex["gene_id"]))
    
    for ex in test_ex:
        if ex.get("gene_id"):
            test_genes.update(_extract_gene_components(ex["gene_id"]))
    
    intersection = train_genes & test_genes
    if intersection:
        raise CriticalLeakageError(
            f"Data leakage detected: {len(intersection)} genes appear in both "
            f"train and test splits: {list(intersection)[:10]}..."
        )
    
    results["leakage_pass"] = True
    results["n_train_genes"] = len(train_genes)
    results["n_test_genes"] = len(test_genes)
    
    # Check 2: Template diversity
    for modality in ["mave", "scrna", "crispr"]:
        modality_examples = [ex for ex in train_ex if ex.get("modality") == modality]
        if not modality_examples:
            continue
        
        # Extract user message (index 1) content
        templates = []
        for ex in modality_examples:
            messages = ex.get("messages", [])
            if len(messages) > 1:
                user_content = messages[1].get("content", "")
                templates.append(extract_template(user_content))
        
        if templates:
            counter = Counter(templates)
            max_freq = max(counter.values()) / len(templates)
            results[f"template_diversity_{modality}"] = max_freq
            results[f"template_pass_{modality}"] = max_freq <= 0.60
    
    # Check 3: BIO_CONTEXT_TOKEN presence
    bio_examples = [ex for ex in train_ex if ex.get("has_bio_context")]
    if bio_examples:
        with_token = sum(
            1 for ex in bio_examples 
            if BIO_CONTEXT_TOKEN in ex.get("messages", [{}])[1].get("content", "")
        )
        coverage = (with_token / len(bio_examples)) * 100
        results["bio_token_coverage_pct"] = coverage
        results["bio_token_pass"] = coverage == 100.0
    
    # Overall pass
    pass_keys = [k for k in results if k.endswith("_pass")]
    results["pass"] = all(results[k] for k in pass_keys)
    
    return results


# Make CriticalLeakageError available at module level for validate_pipeline.py
CriticalLeakageError = SplitError  # Alias for compatibility


# ---------------------------------------------------------------------------
# MODULE ENTRY POINT
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    # Example usage with mock data structure
    print("Module 4: Import and use build_corpus() with Module 1 and 2 outputs.")
    print("See docstring for integration details.")